platform :osx, '10.14'
use_frameworks!

target 'monarch_macos' do
  pod 'FlutterMacOS'
  # Add plugins as needed
end

# The post_install block is optional but recommended if users encounter 
# version mismatches between their SDK and the Pods-embedded framework.
post_install do |installer|
  sdk_framework_path = "/Users/aesakamar/Code/Aesa/cat_games/monarch_local/platform/macos/ephemeral/FlutterMacOS.framework"
  script_path = "Pods/Target Support Files/Pods-monarch_macos/Pods-monarch_macos-frameworks.sh"
  
  if File.exist?(script_path)
    contents = File.read(script_path)
    contents.gsub!(/install_framework "\${PODS_ROOT}\/FlutterMacOS\/FlutterMacOS.framework"/, "install_framework \"#{sdk_framework_path}\"")
    File.open(script_path, "w") { |file| file.puts contents }
  end
end
